POST http://localhost:1337/convert/xml-to-json
Content-Type: application/json

{
  "filename": "MERCHANT_SETTLEMENT_20241120102004_2201.xml"
}

###
POST http://localhost:1337/convert/json-to-csv
Content-Type: application/json

{
  "filename": "MERCHANT_SETTLEMENT_20241120102004_2201.json",
  "jsonPath": "clearing.operation"
}
